language: node_js
node_js:
  - '10'

services:
  - docker

before_install:
  - npm i @microservices/oms

script:
  - npx oms build
  - |
    output="$(npx oms run --silent parse -a url="https://oms.hudson.dev/fixtures/feed-single-item.rss" | jq -c .)"
    if [ "$output" != '{"items":[{"title":"And the Call Was Coming from the Basement","description":null,"summary":null,"date":"2019-10-27T22:00:00.000Z","pubdate":"2019-10-27T22:00:00.000Z","pubDate":"2019-10-27T22:00:00.000Z","link":null,"guid":null,"author":null,"comments":null,"origlink":null,"image":{},"source":{},"categories":[],"enclosures":[{"url":"https://www.podtrac.com/pts/redirect.mp3/podcast.thisamericanlife.org/podcast/319.mp3","type":"audio/mpeg","length":null}],"rss:@":{},"rss:title":{"@":{},"#":"And the Call Was Coming from the Basement"},"rss:pubdate":{"@":{},"#":"Sun, 27 Oct 2019 18:00:00 -0400"},"rss:enclosure":{"@":{"url":"https://www.podtrac.com/pts/redirect.mp3/podcast.thisamericanlife.org/podcast/319.mp3","type":"audio/mpeg"}},"itunes:duration":{"@":{},"#":"59:12"},"meta":{"#ns":[{"xmlns:dc":"http://purl.org/dc/elements/1.1/"},{"xmlns:itunes":"http://www.itunes.com/dtds/podcast-1.0.dtd"}],"@":[{"xml:base":"https://www.thisamericanlife.org"},{"xmlns:dc":"http://purl.org/dc/elements/1.1/"},{"xmlns:itunes":"http://www.itunes.com/dtds/podcast-1.0.dtd"}],"#xml":{"version":"1.0","encoding":"utf-8"},"#type":"rss","#version":"2.0","title":"This American Life","description":null,"date":null,"pubdate":null,"pubDate":null,"link":"https://www.thisamericanlife.org/","xmlurl":null,"xmlUrl":null,"author":null,"language":null,"favicon":null,"copyright":null,"generator":null,"cloud":{},"image":{},"categories":[],"rss:@":{},"rss:title":{"@":{},"#":"This American Life"},"rss:link":{"@":{},"#":"https://www.thisamericanlife.org/"}}}]}' ] ; then echo "$output"; exit 1; fi
